import {Category, IFood } from '../models/food';

export const FoodDirectory: IFood[] = [
      {
        id: 1,
        name: 'Braised Pork with Shrimp paste',
        category: Category.Main,
        imgUrl: '',
        ingredients: ['Pork belly', 'Shallot', 'Spring onions', 'Garlic', 'Chilli', 'Shrimp paste', 'Lemongrass'],
      },
      {
        id: 2, 
        name: 'BBQ Pork',
        category: Category.Main,
        imgUrl: '',
        ingredients: ['Pork belly'],
      }, 
      {
        id: 3, 
        name: 'Braised Pork with Pineapple',
        category: Category.Main,
        imgUrl: '',
        ingredients: ['Pork belly', 'Pineapple', 'Shallot', 'Garlic'],
      },
      {
        id: 4, 
        name: 'Kho quet',
        category: Category.Main,
        imgUrl: '',
        ingredients: ['Pork belly', 'Shallot', 'Garlic'],
      },
      {
        id: 5, 
        name: 'Pork and Egg steamed cake/loafnnn',
        category: Category.Main,
        imgUrl: '',
        ingredients: ['Mince pork', 'Eggs', 'Mushroom', 'Onion'],
      },
      {
        id: 6, 
        name: 'Canh bí đỏ tôm',
        category: Category.Soup,
        imgUrl: '',
        ingredients: ['Tôm', 'Bí đỏ'],
      },
      {
        id: 7, 
        name: 'Canh mồng tơ cua đồng',
        category: Category.Soup,
        imgUrl: '',
        ingredients: ['Mồng tơi', 'Cua đồng'],
      },
      {
        id: 8, 
        name: 'Canh brocoli thịt viên',
        category: Category.Soup,
        imgUrl: '',
        ingredients: ['Brocoli', 'Thit vien'],
      },
      {
        id: 9, 
        name: 'Canh cải thảo',
        category: Category.Soup,
        imgUrl: '',
        ingredients: ['Cải thảo'],
      },
      {
        id: 10, 
        name: 'Snack',
        category: Category.Dessert,
        imgUrl: '',
        ingredients: ['bim bim'],
      },
      {
        id: 11, 
        name: 'Snack 2',
        category: Category.Dessert,
        imgUrl: '',
        ingredients: ['bim bim 2'],
      },
      {
        id: 12, 
        name: 'Snack 3',
        category: Category.Dessert,
        imgUrl: '',
        ingredients: ['bim bim 3'],
      },
      {
        id: 13, 
        name: 'Snack 4',
        category: Category.Dessert,
        imgUrl: '',
        ingredients: ['bim bim 4'],
      },
      {
        id: 14, 
        name: 'Snack 5',
        category: Category.Dessert,
        imgUrl: '',
        ingredients: ['bim bim 5'],
      },
      {
        id: 15, 
        name: 'Snack 6',
        category: Category.Dessert,
        imgUrl: '',
        ingredients: ['bim bim 6'],
      },
]