import { Ingredient } from '../models/Ingredient';

export const ingredientTable: Ingredient[] = [
    {
        id: '1',
        ingredientName: 'Thịt ba rọi',
        ingredientCategory: 'Thịt',
        unit: 'gram',
    },
    {
        id: '2',
        ingredientName: 'Hành khô',
        ingredientCategory: 'Hành',
        unit: 'củ',
    },
    {
        id: '3',
        ingredientName: 'Hành tây',
        ingredientCategory: 'Hành',
        unit: 'củ',
    },
    {
        id: '4',
        ingredientName: 'Tỏi',
        ingredientCategory: 'Hành',
        unit: 'củ',
    },
    {
        id: '5',
        ingredientName: 'Tôm',
        ingredientCategory: 'Hải sản',
        unit: 'gram',
    },
    {
        id: '6',
        ingredientName: 'Ớt',
        ingredientCategory: 'Quả',
        unit: 'trái',
    },
    {
        id: '7',
        ingredientName: 'Xả bầm',
        ingredientCategory: 'Rau',
        unit: 'bịch',
    },
    {
        id: '8',
        ingredientName: 'Mắm ruốc',
        ingredientCategory: 'Gia vị',
        unit: 'lon',
    },
    {
        id: '9',
        ingredientName: 'Trái thơm',
        ingredientCategory: 'Trái cây',
        unit: 'trái',
    },
    {
        id: '10',
        ingredientName: 'Thịt heo băm',
        ingredientCategory: 'Thịt',
        unit: 'gram',
    },
    {
        id: '11',
        ingredientName: 'Trứng',
        ingredientCategory: 'Quả',
        unit: 'trái',
    },
    {
        id: '12',
        ingredientName: 'Nấm đông cô',
        ingredientCategory: 'Nấm',
        unit: 'bịch',
    },
    {
        id: '13',
        ingredientName: 'Lá lốt',
        ingredientCategory: 'Rau',
        unit: 'bó',
    },
    {
        id: '14',
        ingredientName: 'Thịt bò',
        ingredientCategory: 'Thịt',
        unit: 'gram',
    },
    {
        id: '15',
        ingredientName: 'Bông cải xanh',
        ingredientCategory: 'Rau cải',
        unit: 'bông',
    },
    {
        id: '16',
        ingredientName: 'Măng tây',
        ingredientCategory: 'Rau cải',
        unit: 'bó',
    },
    {
        id: '18',
        ingredientName: 'Gừng',
        ingredientCategory: 'Củ',
        unit: 'củ',
    },
    {
        id: '19',
        ingredientName: 'Mực',
        ingredientCategory: 'Hải sản',
        unit: 'gram',
    },
    {
        id: '20',
        ingredientName: 'Tỏi tây',
        ingredientCategory: 'Hành',
        unit: 'củ',
    },
    {
        id: '21',
        ingredientName: 'Cần tây nước',
        ingredientCategory: 'Rau cải',
        unit: 'củ',
    },
    {
        id: '22',
        ingredientName: 'Rau cần tây',
        ingredientCategory: 'Rau cải',
        unit: 'củ',
    },
    {
        id: '23',
        ingredientName: 'Mùi tây',
        ingredientCategory: 'Rau cải',
        unit: 'củ',
    },
    {
        id: '24',
        ingredientName: 'Mồng tơi',
        ingredientCategory: 'Rau cải',
        unit: 'bó',
    },
    {
        id: '25',
        ingredientName: 'Cua đồng',
        ingredientCategory: 'Hải sản',
        unit: 'bịch',
    },
    {
        id: '26',
        ingredientName: 'Thịt bò băm',
        ingredientCategory: 'Thịt',
        unit: 'gram',
    },
    {
        id: '27',
        ingredientName: 'Cải thảo',
        ingredientCategory: 'Rau cải',
        unit: 'bó',
    },
    {
        id: '28',
        ingredientName: 'Sườn heo',
        ingredientCategory: 'Thịt',
        unit: 'gram',
    },
    {
        id: '29',
        ingredientName: 'Xoài',
        ingredientCategory: 'Trái cây',
        unit: 'trái',
    },
    {
        id: '30',
        ingredientName: 'Blueberry',
        ingredientCategory: 'Trái cây',
        unit: 'gói',
    },
    {
        id: '31',
        ingredientName: 'Chuối',
        ingredientCategory: 'Trái cây',
        unit: 'trái',
    },
    {
        id: '32',
        ingredientName: 'Cà rốt',
        ingredientCategory: 'Củ',
        unit: 'củ',
    },
    {
        id: '33',
        ingredientName: 'Bí đỏ',
        ingredientCategory: 'Quả',
        unit: 'củ',
    },
    {
        id: '34',
        ingredientName: 'Cá',
        ingredientCategory: 'Hải sản',
        unit: 'con',
    },
    {
        id: '35',
        ingredientName: 'Bơ',
        ingredientCategory: 'Trái cây',
        unit: 'trái',
    },
    {
        id: '36',
        ingredientName: 'Nếp',
        ingredientCategory: 'Gạo',
        unit: 'gram',
    },
    {
        id: '37',
        ingredientName: 'Chả chiên',
        ingredientCategory: 'Thịt',
        unit: null,
    },
    {
        id: '38',
        ingredientName: 'Chà bông',
        ingredientCategory: '',
        unit: 'hộp',
    },
    {
        id: '39',
        ingredientName: 'Patê',
        ingredientCategory: '',
        unit: 'hộp',
    },
];
